from year2024.day8 import parse_input, calculate_answer1, calculate_answer2

test_input = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""


def test_answer1():
    assert calculate_answer1(parse_input(test_input)) == 14


def test_answer2():
    assert calculate_answer2(parse_input(test_input)) == 34
